spring:
  datasource:
    url: jdbc:h2:mem:acaddb
    username: iamm
    password: 1221
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false